---
# Check to see if CSF is already installed
# TODO: this depends that CSF is in the users path
- name: check if csf is installed
  sudo: true
  command: csf -v
  register: result
  ignore_errors: true

# Create a temp dir for our install
- name: create temp dir
  sudo: true
  command: mkdir -p /tmp/csf
  when: result|failed

# Download the CSF file
- name: download csf files
  sudo: true
  command: "wget https://download.configserver.com/csf.tgz"
  args:
    chdir: /tmp/csf
  when: result|failed

# Extract tar.gz
- name: extract csf files
  sudo: true
  command: tar -zxf csf.tgz
  args:
    chdir: /tmp/csf
  when: result|failed

# Install lib-perl which is sometimes required for retrieving HTTPS URL's
- name: install packages [Debian]
  sudo: true
  apt: name=libwww-perl state=present
  when: "ansible_os_family == 'Debian'"

- name: install packages [RedHat]
  sudo: true
  yum: name=perl-libwww-perl state=present
  when: "ansible_os_family == 'RedHat'"

# Install CSF
- name: install csf
  sudo: true
  command: sh install.sh
  args:
    chdir: /tmp/csf/csf
  when: result|failed

# Cleanup TEMP dir we created
- name: cleanup csf files
  sudo: true
  command: rm -rf /tmp/csf
  when: result|failed
